version: '3.2'
services:
  europe-market:
    image: banitsa/market
    environment:
      SPRING_APPLICATION_JSON: '{ "market.spec.origin": "Europe" }'
    deploy:
      placement:
        constraints: [node.labels.purpose == general-purpose]
  america-market:
    image: banitsa/market
    environment:
      SPRING_APPLICATION_JSON: '{ "market.spec.origin": "America" }'
    deploy:
      placement:
        constraints: [node.labels.purpose == general-purpose]
  asia-market:
    image: banitsa/market
    environment:
      SPRING_APPLICATION_JSON: '{ "market.spec.origin": "Asia" }'
    deploy:
      placement:
        constraints: [node.labels.purpose == general-purpose]

  aurora:
    image: banitsa/aurora
    environment:
      SPRING_APPLICATION_JSON: '{ "grpc.channel.host": "europe-market", "grpc.channel.port": "8080" }'
    deploy:
      placement:
        constraints: [node.labels.purpose == general-purpose]

  orderbook:
    image: banitsa/orderbook
    deploy:
      placement:
        constraints: [node.labels.purpose == general-purpose]

  calculator:
    image: banitsa/calculator
    ports:
      - 80:8080
    deploy:
      placement:
        constraints: [node.labels.purpose == general-purpose]

  dozzle:
    image: amir20/dozzle:v2.0.2
    volumes:
      - type: "bind"
        source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
    ports:
      - 9999:8080
    deploy:
      placement:
        constraints: [node.role == manager]